### ISSUE TITLE
[Feat]: Modification in loading animation

### ISSUE THREAD

**Issue by akash70629** [apurakshit2001/fun-html#1]
**Is your feature request related to a problem? Please describe.**
The loading animation looks boring for users so it can be modified.

**Describe the solution you'd like.**
We can modify the boring animation into a colourful one.

**To Reproduce the problem**
1. Go to the Home page and see it.

**Additional context**

![image](https://github.com/apurakshit2001/fun-html/assets/76689571/3f055892-5f01-4f5f-ba71-19a33cfde873)

**Please checkmark the following checklist**
 - [x] I make sure that a similar issue is not opened

**Comment by apurakshit2001** [comment]
bhalo hoyeche r o valo hote parto by shantanu mAITRA SAREGAMAPA 😁
